# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ofcollage/EES_exp/extral/lab_9_player/WLPlayer/WLPlayer.srcs/sources_1/bd/system/ip/system_audio_formatter_0_0/system_audio_formatter_0_0.xci
# IP: The module: 'system_audio_formatter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ofcollage/EES_exp/extral/lab_9_player/WLPlayer/WLPlayer.gen/sources_1/bd/system/ip/system_audio_formatter_0_0/system_audio_formatter_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_audio_formatter_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ofcollage/EES_exp/extral/lab_9_player/WLPlayer/WLPlayer.gen/sources_1/bd/system/ip/system_audio_formatter_0_0/system_audio_formatter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_audio_formatter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/ofcollage/EES_exp/extral/lab_9_player/WLPlayer/WLPlayer.srcs/sources_1/bd/system/ip/system_audio_formatter_0_0/system_audio_formatter_0_0.xci
# IP: The module: 'system_audio_formatter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ofcollage/EES_exp/extral/lab_9_player/WLPlayer/WLPlayer.gen/sources_1/bd/system/ip/system_audio_formatter_0_0/system_audio_formatter_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_audio_formatter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ofcollage/EES_exp/extral/lab_9_player/WLPlayer/WLPlayer.gen/sources_1/bd/system/ip/system_audio_formatter_0_0/system_audio_formatter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_audio_formatter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
